// Supabase configuration
const SUPABASE_URL = 'https://nvdznelwrkvmbudscqcy.supabase.co';
const SUPABASE_ANON_KEY = 'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im52ZHpuZWx3cmt2bWJ1ZHNjcWN5Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NzA1MjU4NDMsImV4cCI6MjA4NjEwMTg0M30.wSYnP5EFvAmeGXfjgoWmFqyoRXaZgFnaSsqZCdOH4z4';

const supabase = supabase.createClient(SUPABASE_URL, SUPABASE_ANON_KEY);